# Generated by Django 6.0.2 on 2026-09-02 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_assessment_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conversationturn',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1500)]),
        ),
    ]
